// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfgno0QRjepzmgIrJvTCovTQ5Vt4-k9f4',
    appId: '1:1051394559979:web:91885d4e6aee2bb23493ae',
    messagingSenderId: '1051394559979',
    projectId: 'store-app-e6f8d',
    authDomain: 'store-app-e6f8d.firebaseapp.com',
    storageBucket: 'store-app-e6f8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoq23c9QvU7yaQfMHa9rfF1ARnFxZ3etY',
    appId: '1:1051394559979:android:d8c2449eec25518c3493ae',
    messagingSenderId: '1051394559979',
    projectId: 'store-app-e6f8d',
    storageBucket: 'store-app-e6f8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaZAXDTxKS1WWotaAoryy2zy43ijjIaEE',
    appId: '1:1051394559979:ios:4a8c661a6818d5503493ae',
    messagingSenderId: '1051394559979',
    projectId: 'store-app-e6f8d',
    storageBucket: 'store-app-e6f8d.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaZAXDTxKS1WWotaAoryy2zy43ijjIaEE',
    appId: '1:1051394559979:ios:4a8c661a6818d5503493ae',
    messagingSenderId: '1051394559979',
    projectId: 'store-app-e6f8d',
    storageBucket: 'store-app-e6f8d.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfgno0QRjepzmgIrJvTCovTQ5Vt4-k9f4',
    appId: '1:1051394559979:web:362e09f8d3f105503493ae',
    messagingSenderId: '1051394559979',
    projectId: 'store-app-e6f8d',
    authDomain: 'store-app-e6f8d.firebaseapp.com',
    storageBucket: 'store-app-e6f8d.firebasestorage.app',
  );
}
